In [2]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
# python lists
l = range(1000)
%timeit [i**2 for i in l]

259 µs ± 3.83 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
# np array
a = np.arange(1000)
%timeit a**2

1.24 µs ± 26.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
a = np.array([0, 1, 2, 3])
print(a.ndim)
a.shape

1


(4,)

In [10]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b.ndim)
print(b.shape)
len(b) # Size of first dimension

2
(2, 3)


2

In [14]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(c.ndim)
print(c.shape) # return tuple
len(c)
# n dim array are called as tensor

3
(2, 2, 2)


2

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(1, 10, 2) # (start, end(excluded), step)
b

array([1, 3, 5, 7, 9])

In [17]:
a = np.linspace(0, 1, 6) # (start, end, no of points)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
a = np.ones((3, 3)) # (tuple)
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# Identity matrix (diagonal 1 rest 0)
a = np.eye(3, 2) # (row, col)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [21]:
# Diagonal array (diagonal non zero rest zero)
a = np.diag([1, 2, 3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
np.diag(a) # extract diagonal

array([1, 2, 3])

In [24]:
# random no's
a = np.random.rand(4)
a

array([0.04661699, 0.18195651, 0.89522694, 0.26393862])

In [26]:
a = np.random.randn(4)
a

array([-2.1499781 , -0.62951311, -1.54904509,  1.2864531 ])

In [27]:
a = np.arange(10)
a.dtype

dtype('int64')

In [28]:
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
d = np.array([1+2j, 2+4j])
print(d.dtype)

complex128


In [31]:
a = np.arange(10)
print(a)
a[1:8:2] # startindex: endindex(excluded): step

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7])

In [33]:
# mask does deep copy 
a = np.random.randint(0, 20, 15) # (start range, end range, size)
mask = (a % 2 == 0)
mask_a = a[mask]
mask_a

array([18, 14,  6,  6,  2, 10, 12,  4])